### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by georgegeddes** [georgegeddes/pyauric#8]
Oops, I forgot to add one! GPL or BSD? probably GPL, but I'll decide on Monday

**Comment by douglase** [comment]
GPL might not be optimal, since it can inhibit collaboration (see J. VanderPlas' discussion: http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/)
Jake advocates BSD in that blog post, it seems BSD or MIT would be fine: http://choosealicense.com/licenses/, but last time I looked into this I chose Apache 2.0, which seems to cover more scenarios: http://oss-watch.ac.uk/resources/apache2, http://programmers.stackexchange.com/questions/187958/apache-license-and-patents

**Comment by georgegeddes** [comment]
I think a permissive license makes sense for this one because AURIC is under a proprietary license and this code is not very significant. I don't really buy the argument that copyleft inhibits contribution. I think science does need copyleft in the long run because code that is not auditable has no value.

Pull request #10 adds the license.
